## Numpy Library

- Processing N-Dimensional Arrays

In [75]:
import numpy as np
li = [1,2,3]
a = np.array(li)
b = np.arange(15)
c = np.random.randint(0,100,size=10)
m3 = np.random.randint(0,2,size=(3,3))
m4 = np.random.randint(0,2,size=(3,3,3))
m3.ndim  # returns the dimension of the array
m4.size  # returns the size of the array
m3.shape # returns the no.of rows and no.of columns
m3.dtype # returns the data type of the array
m3.itemsize
m3.nbytes  # returns the number of bytes required for the array
b[-5:] # arra slicing also works
m3[:2,:2]  # returns first two rows and first two columns of the 2D array
m3[:3,::2]
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [86]:
# b.reshape(5,3)
b=b[::2]
b

array([0])

In [94]:
x=[1,2]
y=[3,4]
np.concatenate([x,y])

array([1, 2, 3, 4])

In [96]:
m3.diagonal()  ## returns the digonal elements in the matirx
m3

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [102]:
m3.T  # returns the Transpose of a matrix

array([[0, 1, 0],
       [0, 0, 1],
       [1, 1, 1]])

## Pandas
#### Use Cases
- Data Cleaning
- Data Transformation
- Data Analysis

#### Notations
- Series
- DataFrames

In [1]:
import pandas as pd

internal1 = {'s1':21, 's2':18, 's3':24}

internal1 = pd.Series(internal1)
internal1

s1    21
s2    18
s3    24
dtype: int64

In [2]:
internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64

In [3]:
final = {'Internal1':internal1, 'Internal2':internal2}
final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [4]:
final = {'Internal1':internal1, 'Internal2':internal2}
final = pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [5]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [6]:
final.values

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [7]:
final.values[2]

array([24, 12], dtype=int64)

In [8]:
final.values[2,0]

24

In [9]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])

Internal1 -  21 , Internal2 -  15
Internal1 -  18 , Internal2 -  18
Internal1 -  24 , Internal2 -  12


In [10]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [11]:
final.loc['3'] = [12,20]
final=final.drop('3')
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [12]:
final


Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [13]:
final.loc['s4']=[2,0]  # To add

In [14]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
s4          2          0

In [15]:
final.drop('s4')  # To delete

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12